### PR TITLE
Mac OS Install Instructions (and binary build script)

### PR DESCRIPTION
**Pull request by nanobeep**
Mac OS installation instructions and also a script for building a Mac OS anchore-cli binary that can be used later if desired.

### CODE REVIEW

**Comment by zhill** [comment]
commits lgtm. Hate to have to bring this up, but reviewing the commit messages, you need to add the Signoff text (see [contributing](https://github.com/anchore/anchore-cli/blob/master/CONTRIBUTING.rst)). Can you either amend the commits to include the signoff or re-submit the PR with new commits with the sign-off. Once we have that, I'm ready to merge.

Thanks @nanobeep.

**Comment by nanobeep** [comment]
Oops! Thanks for the reminder. Sure, I'll add that :)

**Comment by nanobeep** [comment]
Signoff is added.

**Comment by zhill** [comment]
Thanks @nanobeep. Merged!

**Pull request merged**
