### PR TITLE
Add image status column to list image output. Include image status in…

### LINKED ISSUE #95: Show image status in list output
Starting anchore-engine v0.8.0 image deletion is performed asynchronously, wherein the image status reflects the progress of the image through the cleanup workflow. Currently anchore-cli does not expose this attribute in image listing output. It didn't matter as much when the image deletion was synchronous i.e. successful delete response  meant the image would no longer be included in the list. With image deletion performed asynchronously in anchore-engine, the image may continue to be included in the listings/summary views and clients such as anchore-cli should include the image status for clarity and accuracy

### PR DESCRIPTION
**Pull request by nightfurys**
… image get output

Resolves #95

Signed-off-by: Swathi Gangisetty <swathi@anchore.com>

### CODE REVIEW

**Comment by nightfurys** [comment]
Commit adds a new column, Image Status, to image listing output 
```
nightfury$ docker-compose exec api anchore-cli image list
Full Tag                             Image Digest                                                                   Analysis Status        Image Status
docker.io/library/alpine:3.10        sha256:a143f3ba578f79e2c7b3022c488e6e12a35836cd4a6eb9e363d7f3a07d848590        analyzed               active
docker.io/library/alpine:3.11        sha256:39eda93d15866957feaee28f8fc5adb545276a64147445c64992ef69804dbf01        analyzed               deleting
```

And a new attribute by the same name to image get output
```
nightfury$ docker-compose exec api anchore-cli image get docker.io/library/alpine:3.10
Image Digest: sha256:a143f3ba578f79e2c7b3022c488e6e12a35836cd4a6eb9e363d7f3a07d848590
Parent Digest: sha256:f0e9534a598e501320957059cb2a23774b4d4072e37c7b2cf7e95b241f019e35
Analysis Status: analyzed
Image Status: active
Image Type: docker
Analyzed At: 2020-07-29T08:09:24Z
Image ID: be4e4bea2c2e15b403bb321562e78ea84b501fb41497472e91ecb41504e8a27c
Dockerfile Mode: Guessed
Distro: alpine
Distro Version: 3.10.5
Size: 6338560
Architecture: amd64
Layer Count: 1

Full Tag: docker.io/library/alpine:3.10
Tag Detected At: 2020-07-29T08:08:57Z
```

@zhill, underlying apis exposed image status in the response even before my anchore-engine updates (https://github.com/anchore/anchore-engine/issues/502). So this should be backwards compatible and I verified it against an older version anchore-engine, although the image status attribute will always be `active` in older versions

**Comment by alfredodeza** [comment]
Is it possible to have Analysis Status to be "analyzed" when an image has been deleted? I *think* that is not possible, in which case, the "Analysis Status" could be renamed to "Status" which could be one of: "analyzed" (implicitly stating it is active), "analyzing", or "deleting". 

I tend to prefer not adding any columns at all, or to resist them as much as possible. Hopefully there is room here to avoid one

**Comment by nightfurys** [comment]
> Is it possible to have Analysis Status to be "analyzed" when an image has been deleted?

Once the image is deleted, it will no longer be in the list output. There is no `deleted` image status. 

> I tend to prefer not adding any columns at all, or to resist them as much as possible. Hopefully there is room here to avoid one

Yeah, I agree. Two columns indicating different statuses that may be a bit confusing to the end user. I like the idea of combining both the statuses where the status could reflect the analysis state as long as the image state is active, otherwise fall back to image state. So possible values would be `not_analyzed` `analyzing` `analyzed` `deleting`

**Comment by nightfurys** [comment]
To be clear what I stated above would just be handling on the client side. The API responses from anchore engine will remain untouched. @alfredodeza @zhill, does that sound okay?

**Comment by alfredodeza** [comment]
> To be clear what I stated above would just be handling on the client side. The API responses from anchore engine will remain untouched. @alfredodeza @zhill, does that sound okay?

That sounds great to me

**Comment by zhill** [comment]
I like having the column in the 'full' output, but I think we can omit it in the regular output. Given the API tweak we made I don't think a hybrid state column is a good idea since there is not an actual state in the API that it maps to.

**Comment by alfredodeza** [comment]
> I like having the column in the 'full' output, but I think we can omit it in the regular output. Given the API tweak we made I don't think a hybrid state column is a good idea since there is not an actual state in the API that it maps to.

Is having a 1:1 mapping between API and anchore-cli output a hard requirement? I don't think we follow that strictly

**Comment by nightfurys** [comment]
Closing this PR as its no longer required to support backwards compatibility. Will open another PR to add the full output option that includes showing images in all states. That's a different/bigger change than just exposing a new attribute from the API response

**Pull request closed without merging**
