### PR TITLE
Add initial pytest support

### PR DESCRIPTION
**Pull request by CameronLonsdale**

### CODE REVIEW

**Comment by zhill** [comment]
Hi @CameronLonsdale , I forgot in a previous PR, but I need you to sign the contributors agreement in your commits (e.g. git commit -s), which adds the 'signed-off' string. I'll need those in order to later merge this into master.

**Comment by CameronLonsdale** [comment]
Hi @zhill, apologies that is quite new to me. I have updated this PR to include the sign off for the latest commit and also the previous commit. If you would like to reset the head of python3 branch by 1 and then you can merge this PR and it will solve the issue :)

**Comment by zhill** [comment]
@CameronLonsdale no worries. I'll handle the merge/rebase stuff. I'm in the middle of some other stuff now, but I'll merge this in when I get a chance. Thanks!

**Comment by CameronLonsdale** [comment]
Awesome @zhill ! I'll continue writing tests in a similar way at my leisure

**Comment by zhill** [comment]
@CameronLonsdale I've had to rebase this branch to get the current code into it, but it looks like it causes issues with this PR (note the merge commit list is 5, not the expected 2 or 3). Can I ask you to fetch the latest python3 branch and rebase your changes on it? That should clear things up. Then I'll re-check this PR and merge it if it looks good. Apologies for the extra work. This branch tends to conflict with all the master branch commits, so things get complicated. We'll be merging this back to master as soon as we can so that things clean up.

**Comment by zhill** [comment]
@CameronLonsdale one more update: we've merged the python3 branch into master, so I'm going to close this PR and ask you to re-submit a PR against the master branch and we can work from there instead. Thanks!

**Comment by zhill** [comment]
I'm going to close this PR soon if there is no update, @CameronLonsdale. If you can resolve the merge conflicts and get it updated I'm happy to merge, but otherwise we can just close this an do a new PR later if you'd like to continue the work.

**Comment by CameronLonsdale** [comment]
I'm unable to continue the work at this time @zhill , happy to close this PR.

**Pull request closed without merging**
