### PR TITLE
Removed wait for disabled groups in feed

### LINKED ISSUE #138: "anchore-cli system wait" endlessly waiting for disabled feeds to sync
We currently have the problem, that our scan pipeline is hanging, because it is stuck on waiting:

    $ anchore-cli system wait      
    Starting checks to wait for anchore-engine to be available timeout=-1.0 interval=5.0
    API availability: Checking anchore-engine URL (http://anchore-engine-anchore-engine- 
    api.anchore.svc.cluster.local:8228/v1/)...
    API availability: Success.
    Service availability: Checking for service set (catalog,apiext,policy_engine,simplequeue,analyzer)...
    Service availability: Success.
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    Feed sync: Checking sync completion for feed set (vulnerabilities)...
    [and so on ...]

Running with debug ouput shows:

    ...
    DEBUG:anchorecli.cli.system:response shows group name=ubuntu:14.10 was last_sync=2020-12- 15T14:00:02.497251
    DEBUG:anchorecli.cli.system:response shows group name=centos:5 was last_sync=None
    DEBUG:anchorecli.cli.system:response shows feed name=nvdv2 was last_full_sync=2020-12-15T14:00:52.906874
    DEBUG:anchorecli.cli.system:response shows feed name=github was last_full_sync=2020-12-15T14:00:56.900292
    DEBUG:anchorecli.cli.system:some feeds not yet synced {'vulnerabilities': False}

The centos feeds were disabled:

    $ anchore-cli system feeds list  
    Feed                   Group                     LastSync                          RecordCount    
    ...
    vulnerabilities        amzn:2                    2020-12-15T14:00:18.990919        510                
    vulnerabilities        centos:5(disabled)        -                                 0                  
    vulnerabilities        centos:6(disabled)        -                                 0                  
    vulnerabilities        centos:7(disabled)        -                                 0                  
    vulnerabilities        centos:8(disabled)        -                                 0                  
    vulnerabilities        debian:10                 2020-12-15T14:00:14.715920        24048              
    vulnerabilities        debian:11                 2020-12-15T14:00:21.483493        21322 
    ...

I suspect that this corner case was not thought of in https://github.com/anchore/anchore-cli/pull/116

After enabling the feeds and triggering a sync, "anchore-cli system wait" finishes quickly.

### PR DESCRIPTION
**Pull request by zburstein**
Fixes #138  by checking if group record is disabled before determining if the wait command should wait for the group to sync 

Signed-off-by: Zane Burstein <zane.burstein@anchore.com>

### CODE REVIEW

**Comment by zburstein** [comment]
Initially just made this functionality for a group within a feed because of the example in the issue ticket but Im guessing this functionality should be expanded to entire feeds as well @zhill ? So if the vulnerabilities feed is disabled, the `system wait` command should not wait on that feed?

**Comment by zhill** [comment]
> Initially just made this functionality for a group within a feed because of the example in the issue ticket but Im guessing this functionality should be expanded to entire feeds as well @zhill ? So if the vulnerabilities feed is disabled, the `system wait` command should not wait on that feed? Or should the `feedsready` argument to the command take precedence?

The check should account for disabled feeds, not just groups, but if a user specifies a feed to wait for via feedsready then I think the command should return an error if that feed is found to be disabled because it conflicts with what the user has asked and would otherwise result in either the wrong semantics or an infinite wait.

**Review by dakaneye — APPROVED** [review]
LGTM

**Review by zhill — APPROVED** [review]
lgtm

**Pull request merged**
