### PR TITLE
Add max_images_per_account logic to cli

### PR DESCRIPTION
**Pull request by dakaneye**
Relates to fix for https://github.com/anchore/anchore-engine/issues/858
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

### CODE REVIEW

**Comment by zburstein** [comment]
@dakaneye @zhill  Does functionality for setting the selectors when making an archival rule via the cli need to be added?

**Comment by dakaneye** [comment]
> @dakaneye @zhill Does functionality for setting the selectors when making an archival rule via the cli need to be added?

@zburstein are you referring to the exclude selector? The selectors for a basic transition rule are already `@click` options: https://github.com/anchore/anchore-cli/blob/5710569affc92879c8b0801c771ba92d59f620c2/anchorecli/cli/archives.py#L227

**Review by zhill — APPROVED** [review]
lgtm. adding exclusions can be another PR. This looks good for the max_images.

**Comment by zburstein** [comment]
@dakaneye Yeah sorry I did mean the exclude selectors

**Review by zburstein — APPROVED** [review]
lgtm for max images!

**Pull request merged**
