### PR TITLE
Bump six version to 1.15 from 1.14

### PR DESCRIPTION
**Pull request by JulianNeuhaus27**

### CODE REVIEW

**Comment by zhill** [comment]
Thanks @JulianNeuhaus27 we'll take a look!

**Comment by zhill** [comment]
This won't make the 0.9.1 release, but we can probably get it ready for 0.9.2. I'll target it for that and we can merge after 0.9.1 is released in the next couple of days.

**Comment by JulianNeuhaus27** [comment]
Nice! Thank you for the update 😃

**Comment by JulianNeuhaus27** [comment]
@zhill Could this then be merged for the `0.9.2` release?

**Comment by JulianNeuhaus27** [comment]
Maybe `0.9.3` then? 🙈

**Comment by zhill** [comment]
Yes, I'll get this in for the next release.

**Review by zhill — APPROVED** [review]
lgtm

**Pull request merged**
