### PR TITLE
Add a command 'image del-all' which deletes all images

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by zhill** [comment]
Thanks! I this is good, and is a needed feature, but I think I'd like it to work a little bit differently. 

Instead of a `del-all` command how about converting the existing `del` command to accept either 0 or 1 image references (we can extend this to multiple images later), or a `--all` option. Much the same logic and your code would be the code path for the `--all` option handling.

**Comment by ccojocar** [comment]
@zhill Thanks for review. I refactored the code and moved the `del-all` as the option `--all` to `del` command as you suggested in the comments.

**Comment by ccojocar** [comment]
@zhill Do you have any feedback on this? Is it anything what's left to be addressed? Thanks

**Comment by zhill** [comment]
Thanks @ccojocar . Yes, I'll take a look. I just enabled CI on forked PRs as well.

**Comment by zhill** [comment]
@ccojocar can you please rebase this on latest from master and force-push? That will re-run the CI so that I can merge it here. The CI config wasn't correct and wasn't building forked PRs, but is configured now so it should run but needs a new push event to trigger it. If tests look good and merge is clean I'll merge it. Thanks!

**Comment by ccojocar** [comment]
@zhill Thanks for the heads-up. The branch is rebased and the build seems to have been passed.

**Comment by zhill** [comment]
Thanks @ccojocar !

**Pull request merged**
